name: Release

on:
  workflow_dispatch:
    inputs:
      version_number:
        type: string
        description: Version number to use for the build (e.g. `1.0.0`).

permissions:
  contents: write

concurrency:
  group: release

jobs:
  package:
    uses: ./.github/workflows/package.yaml
    secrets: inherit
    with:
      version_number: ${{ inputs.version_number }}

  release:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download installers
        uses: actions/download-artifact@v8
        with:
          pattern: package-*
          merge-multiple: true

      - name: Rename installers
        env:
          # Add a `v` prefix to the version number.
          VERSION: v${{ inputs.version_number }}
        run: |
          mv installer-universal.exe "glazewm-$VERSION.exe"
          mv installer-arm64.msi "standalone-glazewm-$VERSION-arm64.msi"
          mv installer-x64.msi "standalone-glazewm-$VERSION-x64.msi"
          mv installer-universal.dmg "glazewm-$VERSION.dmg"

      - name: Create draft release
        env:
          # Add a `v` prefix to the version number.
          VERSION: v${{ inputs.version_number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$VERSION" \
            --title "$VERSION" \
            --generate-notes \
            --draft \
            "./glazewm-$VERSION.exe#$VERSION for Windows (standard)" \
            "./standalone-glazewm-$VERSION-arm64.msi#$VERSION for Windows (standalone, arm64)" \
            "./standalone-glazewm-$VERSION-x64.msi#$VERSION for Windows (standalone, x64)" \
            "./glazewm-$VERSION.dmg#$VERSION for macOS"
