name: Winget release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@19e706d4c9121098010096f9c495a70a7518b30f
        with:
          identifier: glzr-io.glazewm
          installers-regex: 'glazewm-v[0-9.]+\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
          fork-user: glzr-io
